### PR TITLE
Simplify docs

### PR DESCRIPTION
**Pull request by jamesp**
This PR simplifies the docs build process to remove custom tooling for API generation, instead use the defaults.

This also adds CI tests for the docs, closing #69.

### CODE REVIEW

**Comment by jamesp** [comment]
This also closes #71

**Review by lbdreyer — APPROVED** [review]
All looks good to me! Very nice to get rid of the custom sphinx stuff!

I will merge this once #68 is in

**Comment by jamesp** [comment]
The docs test pass locally when #67 is included.

**Comment by trexfeathers** [comment]
> The docs test pass locally when #67 is included.

Guess we should wait for @bjlittle's opinion then?

**Pull request merged**
