### PR TITLE
Increase hamming distance for image tests

### PR DESCRIPTION
**Pull request by jamesp**

### CODE REVIEW

**Comment by jamesp** [comment]
This will need to be merged before #69 and #70 to get the tests to pass

**Comment by jamesp** [comment]
> Is it that you think the hamming distance is too fine a comparison?

Yes, can I see no perceptable differences in these two images. If we keep the hamming distance at the low value, which we can if that is what we prefer, it will mean adding more image versions to the test database that will all be very similar. This seems like a lot of admin overhead for little test safety.

**Comment by lbdreyer** [comment]
I would merge this in, but unfortunately I only realised now that I don't have merge permissions on this repo!
@trexfeathers may have merge permissions. I see you are a member of the [tephi dev team](https://github.com/orgs/SciTools/teams/tephi-devs)

**Comment by trexfeathers** [comment]
>@trexfeathers may have merge permissions. I see you are a member of the [tephi dev team](https://github.com/orgs/SciTools/teams/tephi-devs)

I can merge, and I can't give anyone else permissions, so I'll have to!

**Review by trexfeathers — APPROVED** [review]

**Pull request merged**
