### PR TITLE
Paint it black

### PR DESCRIPTION
**Pull request by bjlittle**
Purge `travis` and `sticker` YAMLs

### CODE REVIEW

**Comment by trexfeathers** [comment]
Why haven't the tests run? Does something in GHA need changing to `main`?

**Comment by jamesp** [comment]
@trexfeathers yes they do, good spot

**Comment by bjlittle** [comment]
i'll tweak this pr...

**Comment by bjlittle** [comment]
@jamesp BTW I turned on `pre-commit.ci` :+1:

**Pull request merged**
