### PR TITLE
Removed utils and scooby

### PR DESCRIPTION
**Pull request by jamesp**
This PR removes a dependency (scooby) and the `utils/report` module which appear to be unrelated to the core tephigram functionality.

### CODE REVIEW

**Comment by lbdreyer** [comment]
Looks like this was originally added in https://github.com/SciTools/tephi/pull/58
I don't have a particularly strong preference for whether we keep it or not (although I do prefer a smaller codebase!)
It may be worth checking with @bjlittle ?

**Comment by jamesp** [comment]
I'm not convinced as to what this adds (for the user) over doing:

```
$ conda info
$ conda list
```

Or for the user to install scooby themselves and do `scooby.Report()` on the command line.

For the developer it caused errors in the documentation build that I had to resolve, and is an additional dependency we have to stay on top of.

My vote: Benefits do not outweigh the overhead. But happy to keep it in if it is demonstratably useful

**Comment by trexfeathers** [comment]
> My vote: Benefits do not outweigh the overhead.

I'm inclined to agree. Investigating bugs usually needs back-and-forth anyway, so we'd be able to get the information in conversation with the raiser, and without the extra architecture.

**Comment by bjlittle** [comment]
@jamesp It is unrelated to the core of `tephi` and I'm happy to nuke it.

I was exploring the option of giving users an really simple one-liner option to capture their environment package dependency setup when reporting an issue, with the aim to helping `tephi` developers.

TBH it's a bit over-engineered and not worth the baggage, so let's purge it :+1:

**Comment by bjlittle** [comment]
@jamesp Can you also remove the reference to `tephi/utils/*` in the `.coveragerc`, then we're good to bank this :+1:

**Pull request merged**
